In [1]:
import numpy as np


In [2]:
emp=np.empty([2,2])
print(emp)

[[0.0000000e+000 1.1509914e-311]
 [1.1509914e-311 1.1509914e-311]]


In [14]:
z=np.zeros(shape=[3,3],dtype='int32')
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
o = np.ones(shape=[3,3],dtype='float64')
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
## using of full

In [6]:
f = np.full(shape=[5,5],fill_value=32)
print(f)

[[32 32 32 32 32]
 [32 32 32 32 32]
 [32 32 32 32 32]
 [32 32 32 32 32]
 [32 32 32 32 32]]


In [7]:
##identity matrix
i =np.eye(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
#np.arange()
a=np.arange(1,20,2)
print(a)
a=a.reshape([2,5])
print(a)

[ 1  3  5  7  9 11 13 15 17 19]
[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [9]:
##np.linspace
l=np.linspace(5,20,10)
print(l)
print(len(l))

[ 5.          6.66666667  8.33333333 10.         11.66666667 13.33333333
 15.         16.66666667 18.33333333 20.        ]
10


## new day

In [12]:
import numpy as np

l=np.linspace(5,20,10,retstep=True)
print(l)
print(len(l))

(array([ 5.        ,  6.66666667,  8.33333333, 10.        , 11.66666667,
       13.33333333, 15.        , 16.66666667, 18.33333333, 20.        ]), np.float64(1.6666666666666667))
2


In [20]:
#np.asarray
lst=[10,20,30,40,50]
print(type(lst))
ar=np.asarray(lst)
print(type(ar))
print(lst)
print(ar)

<class 'list'>
<class 'numpy.ndarray'>
[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [21]:
tup=(12,43,5,23,65)
ar=np.asarray(tup)
print(type(ar))
print(tup)
print(ar)

<class 'numpy.ndarray'>
(12, 43, 5, 23, 65)
[12 43  5 23 65]


In [24]:
#copy of array to another
a=np.array([2,4,5,7,9])
b=np.copy(a)
print(b)

[2 4 5 7 9]


In [29]:
ite=(range(100))
arr=np.fromiter(ite,dtype='float64')
print(arr)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [31]:
a=np.arange(5,dtype='float64')
print(a)
print(a.dtype)

[0. 1. 2. 3. 4.]
float64


In [37]:
# unsigned integer
c=np.array([1,2,3],dtype=np.uint16)
print(c)
print(c.dtype)

[1 2 3]
uint16


In [43]:
a=np.array([True,True,False])
print(a.dtype)
print(a)
a=a.astype(float)
print(a.dtype)
print(a)

bool
[ True  True False]
float64
[1. 1. 0.]


In [45]:
b = np.array([4,6,7,8,2])
c=b.astype(complex)
print(b)
print(c)
print(c.dtype)

[4 6 7 8 2]
[4.+0.j 6.+0.j 7.+0.j 8.+0.j 2.+0.j]
complex128


In [4]:
import numpy as np
a=np.arange(10,21)
print(a)
print(a[5])#acces from index

[10 11 12 13 14 15 16 17 18 19 20]
15


In [15]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a[0,2])
print(a[1,0])

[[1 2 3]
 [4 5 6]]
3
4


In [16]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
a[0,1]=10
a[1,1]=20
print(a)

[[1 2 3]
 [4 5 6]]
[[ 1 10  3]
 [ 4 20  6]]


In [23]:
#slicing
a=np.arange(10)
print(a)
print(a[2:6])
a[5:8]=20
print(a)

[0 1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[ 0  1  2  3  4 20 20 20  8  9]
